### ISSUE TITLE
FTBFS fmpz_mod_poly_zero et al

### ISSUE THREAD

**Issue by jengelh** [wbhart/flint2#838]
Compile error with latest trunk 3250b2442 when NTL is enabled:

```
make[2]: Leaving directory '~flint2/fq_zech_mpoly_factor'
make[2]: Entering directory '~flint2'
    CXX   build/interfaces/NTL-interface.lo
interfaces/NTL-interface.cpp: In function ‘void fmpz_mod_poly_set_ZZ_pX(fmpz_mod_poly_struct*, const NTL::ZZ_pX&)’:
interfaces/NTL-interface.cpp:192:31: error: too few arguments to function ‘void fmpz_mod_poly_zero(fmpz_mod_poly_struct*, const fmpz_mod_ctx_struct*)’
  192 |         fmpz_mod_poly_zero(rop);
      |                               ^
In file included from ~flint2/NTL-interface.h:34,
                 from interfaces/NTL-interface.cpp:25:
~flint2/fmpz_mod_poly.h:263:6: note: declared here
  263 | void fmpz_mod_poly_zero(fmpz_mod_poly_t poly, const fmpz_mod_ctx_t ctx)
      |      ^~~~~~~~~~~~~~~~~~
```

culprit commit 90a936491e

**Comment by wbhart** [comment]
Ah, thank you. @tthsqe12 could you update the NTL code for the new interface in trunk.

**Comment by tthsqe12** [comment]
Yes, I will try to update the peripherals now. the c++ interface is going to be a doozy. :(

**Comment by wbhart** [comment]
Oh yes, that could take some time. I guess fmpz_mod_poly is wrapped.

**Comment by wbhart** [comment]
The NTL issue should be fixed in trunk now. The C++ interface remains.
