### ISSUE TITLE
flint-2.4.5 fails to compile with ntl-9.0.2

### ISSUE THREAD

**Issue by tom111** [wbhart/flint2#131]
Hi,

I want to update Gentoo's ntl to the 9.* branch, and flint fails to compile in the NTL interface.  There have been some recent changes in the interface documented here: http://shoup.net/ntl/doc/tour-changes.html

make[3]: Entering directory '/var/tmp/portage/sci-mathematics/flint-2.4.5/work/flint-2.4.5'
x86_64-pc-linux-gnu-g++ -fPIC -march=native -O2 -pipe -DFLINT_CPIMPORT=\"/usr/share/flint/CPimport.txt\" -I/var/tmp/portage/sci-mathematics/flint-2.4.5/work/flint-2.4.5 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -c interfaces/NTL-interface.cpp -o build/interfaces/NTL-interface.lo;
In file included from interfaces/NTL-interface.cpp:37:0:
/usr/include/NTL/g_lip.h: In function ‘long int _ntl_gmaxalloc(_ntl_gbigint)’:
/usr/include/NTL/g_lip.h:410:10: error: redefinition of ‘long int _ntl_gmaxalloc(_ntl_gbigint)’
     long _ntl_gmaxalloc(_ntl_gbigint x)
          ^
In file included from /usr/include/NTL/lip.h:12:0,
                 from /usr/include/NTL/ZZ.h:18,
                 from interfaces/NTL-interface.cpp:32:
/usr/include/NTL/g_lip.h:410:10: note: ‘long int _ntl_gmaxalloc(_ntl_gbigint)’ previously defined here
     long _ntl_gmaxalloc(_ntl_gbigint x)
          ^
Makefile:244: recipe for target 'build/interfaces/NTL-interface.lo' failed

**Comment by wbhart** [comment]
Thanks. We haven't had a chance to update for the latest NTL yet, since our
most recent version was made before it existed.

We'll fix this at the next release.

Bill.

**Comment by kiwifb** [comment]
This problem is solved by https://github.com/wbhart/flint2/pull/95 which was merged into master but not in the 2.4 branch. Which is why it wasn't included in the current 2.4.5. You'll have to include that ntl62 patch in the main tree Thomas!

**Comment by tom111** [comment]
Alright thanks.  I added the patch to the ebuild and it works.
